name: myenv
channels:
  - conda-forge
dependencies:
  - cartopy
  - geopandas
  - pangeo-notebook==2021.02.07
  - xarray
  - jupyterlab
  - hvplot
  - matplotlib
  - rasterio
  - holoviews
  - bokeh
  - datashader
  - contextily
  - dask-gateway
  - rioxarray
  - pip
  - pip:
    - sat-search
